### ISSUE TITLE
Settings View

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#193]
Omnivore is cleaning up the settings and installation views in our web app based on new designs. Most of these pages are already created but need layout and display changes. The settings view work is prioritized and split into separate issues below based on the importance of each view. 

<img width="936" alt="Screen Shot 2022-03-06 at 10 17 36" src="https://user-images.githubusercontent.com/75189/156936426-981ec601-e1c9-4697-bb18-a0932d839c2b.png">

Figma: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=444%3A30941 

## Implementation Plan

1. `Emails and Installation`: The most time sensitive view is the `Emails` view. This can be implemented before the main index as we will link directly to it in our dropdown menu. This means we do not need to implement the side menu on the emails desktop page right away.

2. `Index` After Emails, and installation are implemented we can add the side menu on the emails and installation page, and add the index page for the mobile view.

3. `Labels` view

## Prioritized implementation order:

- [ ] [Emails view](https://github.com/omnivore-app/omnivore/issues/189)
- [ ] [Installation View](https://github.com/omnivore-app/omnivore/issues/192)
- [ ] [Index View](https://github.com/omnivore-app/omnivore/issues/191)
- [ ] [Labels View](https://github.com/omnivore-app/omnivore/issues/190)
