### ISSUE TITLE
MD Release tracking

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1966]
Bugs:

- [x] iOS highlight rendering 
- [x] Safari highlights view focus
- [x] Deleted item refresh

Testing
- [x] Document notes in PDFs
- [x] Highlight notes in PDFs
- [x] PDF highlight layouts

**Comment by jacksonh** [comment]
Looks like all the major issues are working now.
